Models/Noticia.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System;

namespace MovieAppWeb.Models;

public class Noticia
{
    public int ID { get; set; }

    public string Titulo { get; set; }

    public string Genero { get; set; }

    public DateTime Fecha { get; set; }

    public string contenido { get; set; }

    public string Imagen { get; set; }

    [ValidateNever]
    public Usuario Usuario { get; set; }
    public int UsuarioId { get; set; }
}

Controllers/NoticiaController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MovieAppWeb.Data;
using MovieAppWeb.Models;

namespace MovieAppWeb.Controllers;

    public class NoticiaController : Controller
    {

        private readonly ILogger<HomeController> _logger;
        private readonly MovieContext _context;

        public NoticiaController(ILogger<HomeController> logger,
            MovieContext context)
        {
                _logger = logger;
                _context = context;
        }

        public IActionResult AgregarNoticia(){
                return View();
        }

        [HttpPost]
        public IActionResult AgregarNoticia (Noticia objNoticia)
        {
            objNoticia.UsuarioId = (int)_context.Usuarios.Where(p => p.Username.Equals(User.Identity.Name)).ToList().First().Id;
            if(ModelState.IsValid){
                _context.Add(objNoticia);
                _context.SaveChanges();
                return RedirectToAction("verNoticia");
            }
            
            return View();            
        }
         public IActionResult EditarNoticia(int? id)
        {
            if(id == null){
                return NotFound();
            }
            var noticia = _context.Noticias.Find(id);
            if(noticia == null){
                return NotFound();
            }
            return View(noticia);
        }

        [HttpPost]
        public IActionResult EditarNoticia(int id, Noticia objNoticia)
        {
            if (ModelState.IsValid)
            {
                objNoticia.UsuarioId = (int)_context.Usuarios.Where(p => p.Username.Equals(User.Identity.Name)).ToList().First().Id;
                _context.Update(objNoticia);
                _context.SaveChanges();
                return RedirectToAction("VerNoticia");
            }
            return View();
        }

        public IActionResult BorrarNoticia(int? id)
        {
            var noticia = _context.Noticias.Find(id);
            _context.Noticias.Remove(noticia);
            _context.SaveChanges();
            return RedirectToAction(nameof(VerNoticia));
        }

        public IActionResult VerNoticia(){
            var listNoticia=_context.Noticias.OrderBy(s=>s.ID) .ToList();
            return View(listNoticia);
        }       
        public IActionResult VerNoticia2(){
                return View();
        }
        public IActionResult VerNoticia3(){
                return View();
        }
      
    }

Views/Noticia/AgregarNoticia.cshtml
@model MovieAppWeb.Models.Noticia;
@{
    ViewData["Title"] = "Agregar noticia";
}
<h1>@ViewData["Title"]</h1>

<div class="container">
    <form method="post">
        <div class="form-group">
            <label asp-for="Titulo">Título</label>
            <input asp-for="Titulo" class="form-control" placeholder="Título">
        </div>

        <div class="form-group">
            <label asp-for="Genero">Seleccione Género</label>
            <select asp-for="Genero" class="form-control">
                <option>Acción</option>
                <option>Comedia</option>
                <option>Drama</option>
                <option>Romance</option>
                <option>Ciencia y ficción</option>
                <option>Terror</option>
                <option>Suspenso</option>
            </select>
        </div>

        <div class="form-group">
            <label asp-for="Fecha">Fecha</label>
            <input asp-for="Fecha" class="form-control" placeholder="Fecha">
        </div>

        <div class="form-group">
            <label asp-for="contenido">Contenido</label>
            <textarea asp-for="contenido" placeholder="Contenido" class="form-control" cols="30" rows="10"></textarea>
        </div>

        <div class="form-group">
            <label asp-for="Imagen">Url de la imagen</label>
            <input asp-for="Imagen" class="form-control">
        </div>


        <div class="text-center">
            <input type="submit" class="btn btn-primary" value="Agregar noticia">
    </form>

</div>

Views/Noticia/CatalogoNoticia.cshtml
@model IEnumerable<MovieAppWeb.Models.Noticia>


<h2>¡Noticias de usuarios!</h2>


<table class="table table-hover table-responsive">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.contenido)
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">
                    <img src="@Html.DisplayFor(modelItem => item.Imagen)" width="100px">
                    <a asp-action="EditarNoticia" asp-route-id="@item.ID">Editar</a> |
                    <a asp-action="BorrarNoticia" asp-route-id="@item.ID">Borrar</a>
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genero)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.contenido)
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Noticia/EditarNoticia.cshtml
@model MovieAppWeb.Models.Noticia;
@{
    ViewData["Title"] = "Editar noticia";
}
<h1>@ViewData["Title"]</h1>
<div class="container">

    <form method="post">
        <div class="form-group">
            <label asp-for="Titulo">Título</label>
            <input asp-for="Titulo" class="form-control" placeholder="Título">
        </div>

        <div class="form-group">
            <label asp-for="Genero">Seleccione Género</label>
            <select asp-for="Genero" class="form-control">
                <option>Acción</option>
                <option>Comedia</option>
                <option>Drama</option>
                <option>Romance</option>
                <option>Ciencia y ficción</option>
                <option>Terror</option>
                <option>Suspenso</option>
            </select>
        </div>

        <div class="form-group">
            <label asp-for="Fecha">Fecha</label>
            <input asp-for="Fecha" class="form-control" placeholder="Fecha">
        </div>

        <div class="form-group">
            <label asp-for="contenido">Contenido</label>
            <input asp-for="contenido" class="form-control" placeholder="Contenido">
        </div>

        <div class="form-group">
            <label asp-for="Imagen">Url de la imagen</label>
            <input asp-for="Imagen" class="form-control">
        </div>


        <div class="text-center">
            <input type="submit" class="btn btn-primary" value="Editar noticia">
    </form>

</div>

Views/Noticia/VerNoticia.cshtml
@model List<Noticia>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">

    <title>Blog Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/blog/">

    <!-- Bootstrap core CSS -->
    <link href="/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">




    <style>
        a {
            color: #ffffff;
            text-decoration: none;
        }

            a:hover {
                color: #ffffff;
                text-decoration: none;
                cursor: pointer;
            }


        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }


        .hola {
            position: relative;
            top: 30px;
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="blog.css" rel="stylesheet">
</head>

<body>
    <h1 style="text-align: center;">Noticias del canal</h1>


    <!--
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            <li class="page-item">
              <a class="page-link" asp-controller="Noticia" asp-action="VerNoticia3" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            <li class="page-item"><a class="page-link" asp-controller="Noticia" asp-action="VerNoticia">1</a></li>
            <li class="page-item"><a class="page-link" asp-controller="Noticia" asp-action="VerNoticia2">2</a></li>
            <li class="page-item"><a class="page-link" asp-controller="Noticia" asp-action="VerNoticia3">3</a></li>
            <li class="page-item">
              <a class="page-link" asp-controller="Noticia" asp-action="VerNoticia2" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          </ul>
        </nav>
    -->


    <div class="container">


        @for (var i = 0; i < (Model.Count); i++)
        {

            @if (i % 2 == 0)
            {
                <div class="row mb-2">
                    <div class="col-md-11">
                        <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">

                            <div class="hola">
                                <img src="@Html.DisplayFor(modelItem => Model[i].Imagen)" width="165" height="300">
                            </div>
                            <div class="col p-4 d-flex flex-column position-static">

                                <strong class="d-inline-block mb-2 text-primary">@Html.DisplayFor(modelItem => Model[i].Genero)</strong>
                                <h3 class="mb-0">@Html.DisplayFor(modelItem => Model[i].Titulo) </h3>
                                <div class="mb-1 text-muted">@Html.DisplayFor(modelItem => Model[i].Fecha) </div>
                                <p class="card-text mb-auto">@Html.DisplayFor(modelItem => Model[i].contenido) </p>
                                <br>
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <button class="btn btn-primary">
                                        <a asp-action="EditarNoticia" asp-route-id="@Model[i].ID">Editar</a>
                                    </button>

                                    <button class="btn btn-danger">
                                        <a asp-action="BorrarNoticia" asp-route-id="@Model[i].ID">Borrar </a>
                                    </button>

                                }
                            </div>
                        </div>
                    </div>
                </div>
            }
            else
            {
                <div class="row mb-2">
                    <div class="col-md-11">
                        <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                            <div class="col p-4 d-flex flex-column position-static">

                                <strong class="d-inline-block mb-2 text-primary">@Html.DisplayFor(modelItem => Model[i].Genero)</strong>
                                <h3 class="mb-0">@Html.DisplayFor(modelItem => Model[i].Titulo) </h3>
                                <div class="mb-1 text-muted">@Html.DisplayFor(modelItem => Model[i].Fecha) </div>
                                <p class="card-text mb-auto">@Html.DisplayFor(modelItem => Model[i].contenido) </p>
                                <br>
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <button class="btn btn-primary">
                                        <a asp-action="EditarNoticia" asp-route-id="@Model[i].ID">Editar</a>
                                    </button>

                                    <button class="btn btn-danger">
                                        <a asp-action="BorrarNoticia" asp-route-id="@Model[i].ID">Borrar </a>
                                    </button>
                                }
                            </div>
                            <div class="hola">
                                <img src="@Html.DisplayFor(modelItem => Model[i].Imagen)" width="165" height="300">
                            </div>

                        </div>
                    </div>
                </div>
            }
        }
    </div>





    @if (User.Identity.IsAuthenticated)
    {
        <a class="page-link" asp-controller="Noticia" asp-action="AgregarNoticia" style="text-align: center;">Agregar Noticia</a>
    }


</body>

Views/Noticia/VerNoticia2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">

    <title>Blog Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/blog/">

    <!-- Bootstrap core CSS -->
    <link href="/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">




    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="blog.css" rel="stylesheet">
</head>

<body>
    <h1 style="text-align: center;">Noticias del canal (2)</h1>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                <a class="page-link" asp-controller="Noticia" asp-action="VerNoticia" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <li class="page-item"><a class="page-link" asp-controller="Noticia" asp-action="VerNoticia">1</a></li>
            <li class="page-item"><a class="page-link" asp-controller="Noticia" asp-action="VerNoticia2">2</a></li>
            <li class="page-item"><a class="page-link" asp-controller="Noticia" asp-action="VerNoticia3">3</a></li>
            <li class="page-item">
                <a class="page-link" asp-controller="Noticia" asp-action="VerNoticia3" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>


    <div class="container">

        <div class="row mb-2">
            <div class="col-md-6">
                <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-primary">World</strong>
                        <h3 class="mb-0">Featured post</h3>
                        <div class="mb-1 text-muted">Nov 12</div>
                        <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>

                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <img src="https://s3-us-west-2.amazonaws.com/lasaga-blog/media/images/grupo_imagen.original.jpg" width="200" height="250" alt="">
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-success">Design</strong>
                        <h3 class="mb-0">Post title</h3>
                        <div class="mb-1 text-muted">Nov 11</div>
                        <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>

                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="row mb-2">
        <div class="col-md-6">
            <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-primary">World</strong>
                    <h3 class="mb-0">Featured post</h3>
                    <div class="mb-1 text-muted">Nov 12</div>
                    <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>

                </div>
                <div class="col-auto d-none d-lg-block">
                    <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-success">Design</strong>
                    <h3 class="mb-0">Post title</h3>
                    <div class="mb-1 text-muted">Nov 11</div>
                    <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>

                </div>
                <div class="col-auto d-none d-lg-block">
                    <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                </div>
            </div>
        </div>
    </div>
    </div>


    <a class="page-link" asp-controller="Noticia" asp-action="AgregarNoticia" style="text-align: center;">Agregar Noticia</a>

</body>
</html>

Views/Noticia/VerNoticia3.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">

    <title>Blog Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/blog/">

    <!-- Bootstrap core CSS -->
    <link href="/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">




    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="blog.css" rel="stylesheet">
</head>

<body>
    <h1 style="text-align: center;">Noticias del canal (3)</h1>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                <a class="page-link" asp-controller="Noticia" asp-action="VerNoticia2" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <li class="page-item"><a class="page-link" asp-controller="Noticia" asp-action="VerNoticia">1</a></li>
            <li class="page-item"><a class="page-link" asp-controller="Noticia" asp-action="VerNoticia2">2</a></li>
            <li class="page-item"><a class="page-link" asp-controller="Noticia" asp-action="VerNoticia3">3</a></li>
            <li class="page-item">
                <a class="page-link" asp-controller="Noticia" asp-action="VerNoticia" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>


    <div class="container">

        <div class="row mb-2">
            <div class="col-md-6">
                <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-primary">World</strong>
                        <h3 class="mb-0">Featured post</h3>
                        <div class="mb-1 text-muted">Nov 12</div>
                        <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>

                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <img src="https://s3-us-west-2.amazonaws.com/lasaga-blog/media/images/grupo_imagen.original.jpg" width="200" height="250" alt="">
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-success">Design</strong>
                        <h3 class="mb-0">Post title</h3>
                        <div class="mb-1 text-muted">Nov 11</div>
                        <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>

                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <div class="row mb-2">
        <div class="col-md-6">
            <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-primary">World</strong>
                    <h3 class="mb-0">Featured post</h3>
                    <div class="mb-1 text-muted">Nov 12</div>
                    <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>

                </div>
                <div class="col-auto d-none d-lg-block">
                    <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-success">Design</strong>
                    <h3 class="mb-0">Post title</h3>
                    <div class="mb-1 text-muted">Nov 11</div>
                    <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>

                </div>
                <div class="col-auto d-none d-lg-block">
                    <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                </div>
            </div>
        </div>
    </div>
    </div>

    <a class="page-link" asp-controller="Noticia" asp-action="AgregarNoticia" style="text-align: center;">Agregar Noticia</a>
</body>
</html>