Models/Pelicula.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace MovieAppWeb.Models;

public class Pelicula
{
    public int ID { get; set; }

    [Required(ErrorMessage = "Debe ingresar un Titulo")]
    public string Titulo { get; set; } = "";

    [Required(ErrorMessage = "Ingrese un año")]
    public int? Año { get; set; }

    [Required(ErrorMessage = "Especifique el genero")]
    public string Genero { get; set; } = "";

    [Required(ErrorMessage = "Debe ingresar una sinopsis")]
    public string Sinopsis { get; set; } = "";
    public string Imagen { get; set; } = "";
    public string Trailer { get; set; } = "";

    // Hacer que la propiedad Usuario sea opcional
    public Usuario? Usuario { get; set; }
    public int UsuarioId { get; set; }

    public List<Reseña> Reseñas { get; set; } = [];
}

Controllers/PeliculaController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.Extensions.Logging;
using MovieAppWeb.Models;
using System.Collections.Generic;
using MovieAppWeb.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System.Net.Http.Headers;
using MovieAppWeb.Models.dto;

namespace MovieAppWeb.Controllers;

public class PeliculaController : Controller
{

  private readonly ILogger<HomeController> _logger;
  private readonly MovieContext _context;
  private UserManager<IdentityUser> _um;
  private SignInManager<IdentityUser> _sim;
  private readonly IWebHostEnvironment _environment;


  public PeliculaController(ILogger<HomeController> logger,
      MovieContext context, UserManager<IdentityUser> um, SignInManager<IdentityUser> sim, IWebHostEnvironment environment)
  {
    _logger = logger;
    _context = context;
    _um = um;
    _sim = sim;
    _environment = environment;

  }
  public IActionResult AgregarPelicula()
  {
    return View();
  }
  [HttpPost]
  public IActionResult AgregarPelicula(PeliculaDTO peliculaDTO)
  {
    if (peliculaDTO.ImagenFile == null)
    {
      ModelState.AddModelError("ImagenFile", "Debe seleccionar una imagen");
    }

    if (!ModelState.IsValid)
    {
      Console.WriteLine("Error en la validación");
      return View(peliculaDTO);
    }
    else
    {
      // Formato de nombre de archivo amigable
      string newFileName = Guid.NewGuid().ToString() + Path.GetExtension(peliculaDTO.ImagenFile!.FileName);
      string imageFullPath = Path.Combine(_environment.WebRootPath, "images", newFileName);

      using (var stream = System.IO.File.Create(imageFullPath))
      {
        peliculaDTO.ImagenFile.CopyTo(stream);
      }

      var usuarioId = _context.Usuarios
          .Where(p => p.Username.Equals(User.Identity.Name))
          .Select(p => p.Id)
          .FirstOrDefault();

      var objPelicula = new Pelicula
      {
        Titulo = peliculaDTO.Titulo,
        Año = peliculaDTO.Año,
        Genero = peliculaDTO.Genero,
        Sinopsis = peliculaDTO.Sinopsis,
        Imagen = newFileName,
        Trailer = peliculaDTO.Trailer,
        UsuarioId = usuarioId
      };

      _context.Peliculas.Add(objPelicula);
      _context.SaveChanges();
      Console.WriteLine("Exito en la validación");

      return RedirectToAction("Catalogo", "Pelicula");
    }
  }

  public string ConvertirPelicula(string urlpelicula)
  {
    urlpelicula = urlpelicula.Substring(32, 11);
    var peliculaurl = "https://www.youtube.com/embed/" + urlpelicula;
    return peliculaurl;
  }

  public IActionResult EditarPelicula(int? id)
  {
    if (id == null)
    {
      return NotFound();
    }
    var pelicula = _context.Peliculas.Find(id);
    if (pelicula == null)
    {
      return NotFound();
    }
    return View(pelicula);
  }

  [HttpPost]
  public IActionResult EditarPelicula(int id, Pelicula objPelicula)
  {
    objPelicula.UsuarioId = (int)_context.Usuarios.Where(p => p.Username.Equals(User.Identity.Name)).ToList().First().Id;
    if (ModelState.IsValid)
    {
      if (objPelicula.Trailer.Length > 42)
      {
        objPelicula.Trailer = ConvertirPelicula(objPelicula.Trailer);
      }
      _context.Update(objPelicula);
      _context.SaveChanges();
      return RedirectToAction("Catalogo");
    }
    return View();
  }

  public IActionResult BorrarPelicula(int? id)
  {
    if (id == null)
    {
      return NotFound();
    }

    // Busca la película en la base de datos
    var pelicula = _context.Peliculas.Find(id);
    if (pelicula == null)
    {
      return NotFound();
    }

    // Obtén la ruta completa de la imagen
    var imagePath = Path.Combine(_environment.WebRootPath, "images", pelicula.Imagen);

    // Verifica si el archivo existe y elimínalo
    if (System.IO.File.Exists(imagePath))
    {
      System.IO.File.Delete(imagePath);
    }

    // Elimina la película de la base de datos
    _context.Peliculas.Remove(pelicula);
    _context.SaveChanges();

    return RedirectToAction("MisPeliculas");
  }
  public IActionResult Catalogo()
  {
    var listPelicula = _context.Peliculas.OrderBy(s => s.ID).ToList();
    return View(listPelicula);
  }

  public async Task<IActionResult> VistaPelicula(int? id)
  {
    if (id == null)
    {
      return NotFound();
    }

    var pelicula = await _context.Peliculas.FindAsync(id);
    if (pelicula == null)
    {
      return NotFound();
    }

    var resenas = await _context.Reseñas
                                .Where(x => x.PeliculaId == id)
                                .OrderBy(x => x.Id)
                                .ToListAsync();

    if (resenas.Any())
    {
      ViewBag.resenas = true;
      Random rnd = new Random();
      int minId = resenas.First().Id;
      int maxId = resenas.Last().Id;
      int nrouser = rnd.Next(minId, maxId + 1);

      var selectedResena = await _context.Reseñas.FindAsync(nrouser);
      if (selectedResena != null)
      {
        ViewBag.fecha = selectedResena.Fecha.ToString("dd/MM/yyyy");
        ViewBag.estrellitas = selectedResena.Estrellas;
        ViewBag.resenausuario = selectedResena.Comentario;

        var usuario = await _context.Usuarios.FindAsync(selectedResena.UsuarioId);
        ViewBag.nombreusuario = usuario?.Username;
      }
    }
    else
    {
      ViewBag.resenas = false;
    }

    return View(pelicula);
  }


  // public IActionResult VistaPelicula(int? id)
  // {
  //     var pelicula = _context.Peliculas.Find(id);
  //     ViewBag.resenas = false;
  //     if (_context.Reseñas.Where(x => x.PeliculaId.Equals(id)).Count() > 0)
  //     {
  //         ViewBag.resenas = true;
  //         Random rnd = new Random();
  //         int nrouser = rnd.Next(_context.Reseñas.Where(x=>x.PeliculaId.Equals(id)).OrderBy(x=>x.Id).ToList().First().Id,_context.Reseñas.Where(x=>x.PeliculaId.Equals(id)).OrderBy(x => x.Id).ToList().Last().Id);
  //         ViewBag.fecha = _context.Reseñas.Find(nrouser).Fecha.ToString();
  //         ViewBag.estrellitas = _context.Reseñas.Where(x=>x.PeliculaId.Equals(id)).FirstOrDefault(x=>x.Id.Equals(nrouser)).Estrellas;
  //         ViewBag.nombreusuario = _context.Usuarios.Where(x => x.Id.Equals(_context.Reseñas.Find(nrouser).UsuarioId)).First().Username;
  //         ViewBag.resenausuario = _context.Reseñas.Where(x=>x.PeliculaId.Equals(id)).FirstOrDefault(x=>x.Id.Equals(nrouser)).Comentario;
  //         ViewBag.fecha = _context.Reseñas.Where(x=>x.PeliculaId.Equals(id)).FirstOrDefault(x=>x.Id.Equals(nrouser)).Fecha;
  //     }
  //     if(pelicula == null){
  //         return NotFound();
  //     }
  //     return View(pelicula);
  // }

  [HttpPost]
  public IActionResult Catalogo(string idfiltro, string filtro, string action)
  {
    Console.WriteLine("IdFiltro: " + idfiltro);
    Console.WriteLine("Filtro: " + filtro);
    Console.WriteLine("Action: " + action);

    var listClientes = _context.Peliculas.OrderBy(s => s.ID).ToList();

    if (action == "filter")
    {
      if (idfiltro == "titulo")
      {
        listClientes = _context.Peliculas.Where(c => c.Titulo.ToUpper().Contains(filtro.ToUpper())).OrderBy(s => s.ID).ToList();
      }
      else
      {
        listClientes = _context.Peliculas.Where(c => c.Genero.ToUpper().Contains(filtro.ToUpper())).OrderBy(s => s.ID).ToList();
      }
    }


    // var listClientes=_context.Clientes.Where(c => c.Nombre.ToUpper().Contains(filtro.ToUpper())).OrderBy(s=>s.Id) .ToList();
    return View(listClientes);
  }
  public IActionResult MisPeliculas()
  {
    var listapeliculas = _context.Peliculas.OrderBy(x => x.ID).Where(p => p.Usuario.Username.Equals(User.Identity.Name)).ToList();
    return View(listapeliculas);
  }
  [HttpPost]
  public IActionResult MisPeliculas(string idfiltro, string filtro, string action)
  {
    Console.WriteLine("IdFiltro: " + idfiltro);
    Console.WriteLine("Filtro: " + filtro);
    Console.WriteLine("Action: " + action);
    
    var listapeliculas = _context.Peliculas.OrderBy(x => x.ID).Where(p => p.Usuario.Username.Equals(User.Identity.Name)).ToList();


    if (action == "filter")
    {
      if (idfiltro == "titulo")
      {
        listapeliculas = _context.Peliculas.Where(c => c.Titulo.ToUpper().Contains(filtro.ToUpper())).OrderBy(s => s.ID).ToList();
      }
      {
        listapeliculas = _context.Peliculas.Where(c => c.Genero.ToUpper().Contains(filtro.ToUpper())).OrderBy(s => s.ID).ToList();
      }
    }
    return View(listapeliculas);
  }


}

Controllers/ReseñaController.cs
using System.Linq;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieAppWeb.Data;
using MovieAppWeb.Models;

namespace MovieAppWeb.Controllers;

  public class ReseñaController : Controller
  {
      private readonly MovieContext _context;
      private UserManager<IdentityUser> _um;
      private SignInManager<IdentityUser> _sim;
      public ReseñaController(MovieContext context, UserManager<IdentityUser> um, SignInManager<IdentityUser> sim)
      {
          _context = context;
          _um = um;
          _sim = sim;
      }
      public IActionResult Resena(int? peli)
      {
          if(peli == null)
          {
              return NotFound();
          }
          var resena = _context.Peliculas.Find(peli);
          var infopeli = _context.Reseñas.Find(peli);
          // var infopeli2 = _context.Reseñas.Include(x=> x.Pelicula).Include(y=> y.Usuario).SingleOrDefault(z=> z.Pelicula.ID == peli);
          ViewBag.imgpeli = resena.Imagen;
          ViewBag.titulopeli = resena.Titulo;
          return View();
      }
      [HttpPost]
      public IActionResult resena(int peli, Reseña objResena)
      {
          var resena = _context.Peliculas.Find(peli);
          ViewBag.imgpeli = resena.Imagen;
          ViewBag.titulopeli = resena.Titulo;
          
          if(ModelState.IsValid)
          {
              objResena.Fecha = System.DateTime.Now;
              objResena.PeliculaId = peli;
              objResena.UsuarioId = (int)_context.Usuarios.Where(p => p.Username.Equals(User.Identity.Name)).ToList().First().Id;
              // return BadRequest(objResena);
              _context.Add(objResena);
              _context.SaveChanges();
              return RedirectToAction("Catalogo","Pelicula");
          }
          return View();
      }
      public IActionResult VerResenas(int peli)
      {
          var listaResenas = _context.Reseñas.Include(q=>q.Pelicula).Include(w=>w.Usuario).Where(p=>p.PeliculaId.Equals(peli)).OrderBy(x=>x.Id).ToList();
          var pelicula = _context.Peliculas.Find(peli);
          ViewBag.peli = pelicula.Titulo;
          return View(listaResenas);
      }
  }

Controllers/UsuarioController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieAppWeb.Data;
using MovieAppWeb.Models;

namespace MovieAppWeb.Controllers;

    public class UsuarioController : Controller
    {
        private readonly MovieContext _context;
        private UserManager<IdentityUser> _um;
        private SignInManager<IdentityUser> _sim;
        public UsuarioController(MovieContext context, UserManager<IdentityUser> um, SignInManager<IdentityUser> sim)
        {
            _context = context;
            _um = um;
            _sim = sim;
        }
        public IActionResult Index()
        {
            var listPelicula=_context.Peliculas.OrderBy(s=>s.ID) .ToList();
            return View(listPelicula);
        }

        public IActionResult Registro()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registro(string username, string pwd, Usuario infouser)
        {
            /*console*/

            Console.WriteLine("Username: "+ username);
            Console.WriteLine("pwd: "+ pwd);
            Console.WriteLine("infouser: "+ infouser);

            
            infouser.Username = username;
            infouser.Pwd = pwd;
            if(ModelState.IsValid){
                var IdentityUser = new IdentityUser(username);
                var result =_um.CreateAsync(IdentityUser,pwd).Result;
                if(result.Succeeded)
                {
                    _context.Add(infouser);
                    _context.SaveChanges();
                    return RedirectToAction("login");
                }else{
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("usuario", error.Description);
                    }
                    var result2 =_um.DeleteAsync(IdentityUser).Result;
                    return View();
                }
            }
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(string username, string pwd)
        {
            //alvaro1
            //Servidores5$
            Console.WriteLine("Username: "+ username);
            Console.WriteLine("pwd: "+ pwd);
            var result = _sim.PasswordSignInAsync(username,pwd,false,false).Result;
            if(result.Succeeded)
            {
                return RedirectToAction("index","home");
            }
            ModelState.AddModelError("usuario","Datos incorrectos");
            return View();
        }
        public async Task<IActionResult> logout()
        {
            await _sim.SignOutAsync();
            return RedirectToAction("index","home");
        }
    }

Views/Pelicula/AgregarPelicula.cshtml
@* <link rel="stylesheet" href="~/css/agregarpeli.css" /> *@
@model MovieAppWeb.Models.dto.PeliculaDTO;
@{
    ViewData["Title"] = "Agregar película";
}
<h1>@ViewData["Title"]</h1>

<div class="container">
    <form method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="Titulo">Título</label>
        <input asp-for="Titulo" class="form-control" placeholder="Título" />
    </div>

    <div class="form-group">
        <label asp-for="Año">Año</label>
        <input asp-for="Año" class="form-control" placeholder="Año de estreno" />
    </div>

    <div class="form-group">
        <label asp-for="Genero">Seleccione Género</label>
        <select asp-for="Genero" class="form-control">
            <option>Acción</option>
            <option>Comedia</option>
            <option>Drama</option>
            <option>Romance</option>
            <option>Ciencia y ficción</option>
            <option>Terror</option>
            <option>Suspenso</option>
        </select>
    </div>

    <div class="form-group">
        <label asp-for="Sinopsis">Sinopsis</label>
        <textarea asp-for="Sinopsis" placeholder="Sinopsis de la pelicula" class="form-control" cols="30" rows="10"></textarea>
    </div>

    <div class="form-group">
        <label asp-for="ImagenFile">Subir imagen</label>
        <input asp-for="ImagenFile" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Trailer">Url del trailer</label>
        <input asp-for="Trailer" class="form-control" required />
    </div>

    <div class="text-center">
        <input type="submit" class="btn btn-primary" value="Agregar película" />
        <input type="button" class="btn btn-danger" value="Volver" onclick="location.href='@Url.Action("Index","Home")'" />
    </div>
</form>
</div>

Views/Pelicula/Catalogo.cshtml
@* <link rel="stylesheet" href="~/css/EstilosCatalogo.css"> *@

@model List<Pelicula>

<h2 class="text-center">Lista de Películas</h2>


<style>
    a {
    color: #ffffff;
    text-decoration: none;
}
    a:hover 
{
     color:#ffffff; 
     text-decoration:none; 
     cursor:pointer;  
}


@* img:hover{
    width: 220px;
    height: 290px;
} *@

img{
    box-shadow: 5px 5px 10px
    rgba(0, 0, 0, 0.40);
}


</style>


<form method="POST">
    <label >Filtrar por :</label>
    <select name="idfiltro">
        <option value="titulo">Título</option>
        <option value="genero">Género</option>
    </select>
    <input type="text" name="filtro">
    <button class="btn btn-info" name="action" value="filter" >Filtrar</button>
    <button class="btn btn-warning" name="action" value="all" >Mostrar todo</button>
</form>


<div class="d-flex flex-wrap gap-4 ">
    
        @foreach (var item in Model)
            {
                <div scope="d-flex flex-col">
                    <div class="portafolio
                    -container">
                        <a asp-action="VistaPelicula" asp-route-id="@item.ID">
                            <img class="portafolio-img" width="180px" height="250px" src="@Url.Content("~/images/" + item.Imagen)" />
                        </a>
                        <p>Click para ver detalles</p>
                    </div>
                    <b>Titulo</b>
                    <br>
                    @Html.DisplayFor(modelItem => item.Titulo)
                    <br>
                    <b>Género</b>
                    <br>
                    @Html.DisplayFor(modelItem => item.Genero)
                    <br>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <div class="text-center">
                            <button class="btn btn-primary">
                                <a asp-action="EditarPelicula" asp-route-id="@item.ID">Editar</a>
                            </button>
                        </div>
                    }
                </div>
            }
</div>



@if (User.Identity.IsAuthenticated)
{
    <button type="button" class="btn btn-success"><a asp-action="AgregarPelicula"> Registrar Nueva Película</a></button>
}

Views/Pelicula/EditarPelicula.cshtml
<!--
<link rel="stylesheet" href="~/css/agregarpeli.css" />
-->
@model MovieAppWeb.Models.Pelicula;
@{
    ViewData["Title"] = "Editar película";
}
<h1>@ViewData["Title"]</h1>
<div class="container">

    <form method="post">
        <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="Titulo">Título</label>
            <input asp-for="Titulo" class="form-control" placeholder="Título">
        </div>

        <div class="form-group">
            <label asp-for="Año">Año</label>
            <input asp-for="Año" class="form-control" placeholder="Año de estreno">
        </div>

        <div class="form-group">
            <label asp-for="Genero">Seleccione Género</label>
            <select asp-for="Genero" class="form-control">
                <option>Acción</option>
                <option>Comedia</option>
                <option>Drama</option>
                <option>Romance</option>
                <option>Ciencia y ficción</option>
                <option>Terror</option>
                <option>Suspenso</option>
            </select>
        </div>

        <div class="form-group">
            <label asp-for="Sinopsis">Sinopsis</label>
            <textarea asp-for="Sinopsis" placeholder="Sinopsis de la pelicula" class="form-control" cols="30" rows="10"></textarea>
        </div>

        <div class="form-group">
            <label asp-for="Imagen">Url de la imagen</label>
            <input asp-for="Imagen" class="form-control">
        </div>


        <div class="form-group">
            <label asp-for="Trailer">Url del trailer</label>
            <input asp-for="Trailer" class="form-control" required>
        </div>


        <div class="text-center">
            <input type="submit" class="btn btn-primary" value="Confirmar edicion">
    </form>

</div>

Views/Pelicula/VistaPelicula.cshtml
@model MovieAppWeb.Models.Pelicula
@{
    ViewData["Title"] = "Detalle de la pelicula";
}
<h1 class="text-center">@ViewData["Title"]</h1>

<!--
<style>
.iframe-16-9 {
   position: relative;
   padding-bottom: 56.25%;
   padding-top: 35px;
   height: 0;
   overflow: hidden;
}
.iframe-16-9  iframe {
   position: absolute;
   top:0;
   left: 0;
   width: 100%;
   height: 100%;
}
</style>
-->

<style>
    a {
        color: #ffffff;
        text-decoration: none;
    }

        a:hover {
            color: #ffffff;
            text-decoration: none;
            cursor: pointer;
        }

    h2 {
        background-color: gray;
        color: white;
        border-radius: 10px;
        text-align: center;
    }

    .font20 {
        font-size: 20px;
        font-weight: 300;
    }

    .justificado {
        text-align: justify;
        text- justify: auto;
    }

    .checked {
        color: orange;
    }
</style>


<div class="container">

    <div class="row">
        <div class="col-5">
            <div>
                <img src="~/images/@Url.Content(Model.Imagen)" alt="Imagen de portada" width="100%" />

            </div>
            <br>
            <div>
                @if (User.Identity.IsAuthenticated)
                {
                    <button class="btn btn-warning">
                        <a asp-controller="Reseña" asp-action="Resena" asp-route-peli="@Model.ID"> Escribir Reseña</a>
                    </button>
                }
                @* <button class="btn btn-warning">
                <a asp-controller="Reseña" asp-action="Resena" asp-route-peli="@Model.ID"> Escribir Reseña</a>
                </button> *@
            </div>
        </div>
        <div class="col-7">
            <dl>
                <dt>
                    <h2>
                        Información
                    </h2>
                </dt>
                <br>
                <dt class="font20">
                    @Html.DisplayNameFor(model => model.Titulo) :
                    @Html.DisplayFor(model => model.Titulo)
                </dt>

                <dt class="font20">
                    @Html.DisplayNameFor(model => model.Año) :
                    @Html.DisplayFor(model => model.Año)
                </dt>

                <dt class="font20">
                    @Html.DisplayNameFor(model => model.Genero) :
                    @Html.DisplayFor(model => model.Genero)
                </dt>

            </dl>
            <button type="button" class="btn btn-success">
                <a asp-action="Catalogo"> Regresar al catalogo</a>
            </button>
        </div>
    </div>
    <br>
    <div class="col-12">
        <dt>
            <h2>@Html.DisplayNameFor(model => model.Sinopsis)</h2>
            <div class="justificado">
                @Html.DisplayFor(model => model.Sinopsis)
            </div>
        </dt>
    </div>

    <br>

    <h2>@Html.DisplayNameFor(model => model.Trailer)</h2>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="@Html.DisplayFor(model => model.Trailer)" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>

    <h2 class="mt-3">
        Reseñas de los usuarios @if (@ViewBag.resenas)
        {
            <a asp-action="VerResenas" asp-controller="Reseña" asp-route-peli="@Model.ID" class="btn btn-warning">Ver todas las reseñas</a>
        }
    </h2>
    @if (@ViewBag.resenas)
    {
        @* <div class="text-center">
    <label for="">&#9734; &#9734; &#9734; &#9734; &#9734; <small>@ViewBag.estrellitas/5</small></label>
    <label for=""> - @ViewBag.nombreusuario</label>
    <br>
    <small><label for="">Publicado: @ViewBag.fecha</label></small>
    <div class="">
    @ViewBag.resenausuario
    </div>
    </div> *@
        <div class="container">
            <div class="row" style="background-color: teal;">
                <div class="col-8">
                    Comentario
                    <small style="margin-left: 15px;">
                        @ViewBag.fecha
                    </small>
                </div>
                <div class="col-4 text-right">
                    <label>
                        @for (int i = 0; i < ViewBag.estrellitas; i++)
                        {
                            <span class="fa fa-star checked"></span>
                        }
                        @for (int i = 0; i < 5 - ViewBag.estrellitas; i++)
                        {
                            <span class="fa fa-star"></span>
                        }
                    </label>
                </div>
            </div>
            <div class="row">
                <div class="col" style="padding-left: 10%; padding-right: 10%; padding-top: 0.5rem; text-align: justify; text-justify: auto;">
                    <i>
                        "@ViewBag.resenausuario"
                    </i>
                </div>
            </div>
            <div class="row">
                <div class="col-8">
                </div>
                <div class="col-4 text-right mb-3">
                    <small>
                        <b>
                            ~@ViewBag.nombreusuario~
                        </b>
                    </small>
                </div>
            </div>
        </div>

    }
    else
    {
        <p>
            Aun no se han agregado reseñas, puedes agregar una
            @if (User.Identity.IsAuthenticated)
            {
                <button class="btn btn-warning">
                    <a asp-controller="Reseña" asp-action="Resena" asp-route-peli="@Model.ID"> Aqui</a>
                </button>
            }
            else
            {
                <button class="btn btn-warning">
                    <a asp-action="Registro" asp-controller="Usuario"> Registrandote aqui</a>
                </button>
            }
        </p>

    }
    <div class="text-center">
        <button type="button" class="btn btn-success mt-2">
            <a asp-action="Catalogo"> Regresar al catalogo</a>
        </button>
    </div>


    <!--
      <dl class="dl-horizontal">
          <dt>
    @Html.DisplayNameFor(model => model.Imagen):
          </dt>
          <dt>
    @Html.DisplayNameFor(model => model.Titulo) :
    @Html.DisplayFor(model => model.Titulo)
          </dt>
          <dt>
    @Html.DisplayNameFor(model => model.Año) :
    @Html.DisplayFor(model => model.Año) :
          </dt>
          <dt>
    @Html.DisplayNameFor(model => model.Genero) :
    @Html.DisplayFor(model => model.Genero)
          </dt>
          <dt>
    @Html.DisplayNameFor(model => model.Sinopsis) :
    @Html.DisplayFor(model => model.Sinopsis)
          </dt>
          <dt class="iframe-16-9">
                                             width="560" height="315"
             <iframe src="@Html.DisplayFor(model => model.Trailer)" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </dt>
      </dl>
    </div>
    -->